// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Emotion = require("bs-emotion/src/Emotion.bs.js");

var flex1 = /* `some */[
  -866639116,
  /* tuple */[
    1,
    1,
    /* zero */-789508312
  ]
];

var app = Emotion.css(undefined, /* :: */[
      Emotion.label("app"),
      /* :: */[
        Emotion.display(/* flex */-1010954439),
        /* :: */[
          Emotion.height(/* `vh */[
                26418,
                100
              ]),
          /* [] */0
        ]
      ]
    ]);

var events = Emotion.css(undefined, /* :: */[
      Emotion.label("events"),
      /* :: */[
        Emotion.width(/* `px */[
              25096,
              200
            ]),
        /* [] */0
      ]
    ]);

var map = Emotion.css(undefined, /* :: */[
      Emotion.label("map"),
      /* :: */[
        Emotion.flex(flex1),
        /* [] */0
      ]
    ]);

exports.flex1 = flex1;
exports.app = app;
exports.events = events;
exports.map = map;
/* app Not a pure module */
